apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rfcxxxx-data-node-1
  namespace: rfcxxxx
  labels:
    app: rfcxxxx
    component: node-1
    storage: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rfcxxxx-data-node-2
  namespace: rfcxxxx
  labels:
    app: rfcxxxx
    component: node-2
    storage: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rfcxxxx-data-node-3
  namespace: rfcxxxx
  labels:
    app: rfcxxxx
    component: node-3
    storage: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rfcxxxx-data-node-4
  namespace: rfcxxxx
  labels:
    app: rfcxxxx
    component: node-4
    storage: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rfcxxxx-shared-data
  namespace: rfcxxxx
  labels:
    app: rfcxxxx
    component: shared
    storage: shared
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
